#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running ESLint..."
cd frontend && npx eslint . --max-warnings=0 || exit 1  # Ensures failure on errors

echo "Running Prettier..."
npx prettier --write . --ignore-path .prettierignore
