#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Get the current branch name
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

# Check if the current branch is "master"
if [ "$CURRENT_BRANCH" != "main" ]; then
  echo "Skipping pre-push checks as the current branch is not 'master'. ✅"
  exit 0
fi

echo "Building Project with pnpm..."
pnpm run build || exit 1  # Stop push if build fails

echo "✅ All checks passed. Pushing..."
